### PR TITLE
Use node type URL

### PR DESCRIPTION
**Pull request by robinjhector**
Instead of the globally "available" DOM URL. Makes it work on pure backend-environments where there is no DOM available

As found out in my own project when bumping to 5.0.0:

```
$ npm run build

> homebridge-tibber-price@1.0.2 build
> rimraf ./dist && tsc

node_modules/tibber-api/lib/src/nodes/TibberQueryBase.d.ts:42:44 - error TS2304: Cannot find name 'URL'.

42     getWebsocketSubscriptionUrl(): Promise<URL>;

```

### CODE REVIEW

**Comment by robinjhector** [comment]
Ping @bisand 👍

**Comment by bisand** [comment]
> Ping @bisand 👍

Sorry for the late reply. I have been a bit occupied with other projects at the moment. Will merge and release a new version.

Thanks for the contribution!
